@host=http://192.168.186.135:9200
@index=asset_proc_history
@type={{index}}
@json=Content-Type:application/json

###
#创建索引

curl -X PUT {{host}}/{{index}} -H {{json}} -d '
{
    "settings": {
        "number_of_shards" :   5,
        "number_of_replicas" : 0
    }
}'

###
curl -X DELETE {{host}}/{{index}}

###
#创建类型
curl -X PUT {{host}}/{{index}}/{{type}}/_mapping -H {{json}} -d '
{
  "properties":{
    "assetId":{ "type":"keyword" },
    "version":{ "type":"long" },
    "collectCount":{ "type":"integer" },
    "collect":{
        "type":"nested",
        "properties":{
            "procName":{ "type":"text","analyzer":"ik_max_word", "search_analyzer":"ik_max_word" },
            "userName":{ "type":"keyword" },
            "pid":{ "type":"keyword" },
            "ppid":{ "type":"keyword" },
            "startTime":{ "type":"keyword" },
            "runTime":{ "type":"keyword" },
            "startFile":{ "type":"keyword" },
            "workPath":{ "type":"keyword" },
            "startCmd":{ "type":"keyword" },
            "procDesc":{ "type":"keyword" }
        }
    }
  }
}
'